TITLE PREKID

ASSUME CS:CSEG, DS:DSEG, ES:DSEG
	PUBLIC SET_NEW_INT_RUT, RETURN_OLD_INT_RUT
	
DSEG SEGMENT PARA PUBLIC 'DATA'

OLD_INT_ADR DW 0h, 0h

DSEG ENDS

CSEG SEGMENT PARA PUBLIC 'CODE'

	SET_NEW_INT_RUT PROC NEAR
		;U MAIN PROGRAMU PRE POZIVA OVOGA MORAMO SMESTITI NOVU ADRESU
		;PREKIDNE RUTINE U DS:DX
		
		MOV AH, 35h ; AH = 35 INT 21h DOHVAATANJA ADRESE PREKIDNE RUTINE(ZA CUVANJE STARE ADRESE KOJU MENJAMO NASOM NOVOM)
		MOV AL, 1Ch
		INT 21h
		
		PUSH DS
		MOV AX, SEG DSEG
		MOV DS, AX
		MOV OLD_INT_ADR, BX
		MOV BX, ES
		MOV OLD_INT_ADR+2, BX ; CUVANJE STARE ADRESE KOJU DOBIJAMO IZ OVOG GORE OS INT
		POP DS
		
		MOV AH, 25h
		MOV AL, 1Ch ; SADA SMESTAMO ADRESU IZ DS:DX NA MESTO OVE STARE GORE
		INT 21h
		
		RET
	
	SET_NEW_INT_RUT ENDP
	
	RETURN_OLD_INT_RUT PROC NEAR
		
		PUSH DS
		
		MOV AX, SEG DSEG
		MOV DS, AX
		MOV DX, OLD_INT_ADR
		MOV AX, OLD_INT_ADR+2
		MOV DS, AX
		
		MOV AH, 25h
		MOV AL, 1Ch
		INT 21h		;KAO I U POSTAVLJANJU OVOM FUNKCIJOM STAVLJAMO ADRESU NA MESTO 1Ch SAMO STO SADA VRACAMO STARU
		
		POP DS
		RET
	
	
	RETURN_OLD_INT_RUT ENDP


CSEG ENDS

END